### ISSUE TITLE
Allow users to configure how puppet libraries are managed for apply_prep

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1123]
# Problem
Currently the `apply_prep` method calls the `puppet_agent::install` task to install the agent. Instead the behavior for this should be configurable via plugins.

### Test Cases

- [X] Configure the `task` plugin to use the `puppet_agent::install` plugin with different arguments.
- [x] Configure the `task` plugin to use the `bootstrap` task to install the agent.
- [x] ~~Use run_as root with the `puppet_agent::install` task.~~ #1191

### New `plugin_hooks` section in bolt.yaml and inventory
plugin_ hook allows users to configure what hooks are used on a per node basis. This section is an object where the keys are hooknames and the value specifies and configures the plugin to use. This key should be set on a target or a group. It should use the same merging strategy(shallow merge) as `vars` does. 

inventory example
```
---
targets:
   - name: foo
      plugin_hooks:
        puppet_library:
          plugin: install_agent
```

config example
```
---
modulepath: [~/modules]
plugin_hooks:
  puppet_library
    plugin: install_agent
```

### puppet_library plugin hook
When the puppet library plugin hook is configured the apply_prep function will run the plugins hook rather then using the builtin logic.

### Task plugin hook for `puppet_library`

In order to let users write their own task or use an existing task we should add a `puppet_library` hook handler to the task plugin.

```
plugin_hooks:
  puppet_library:
    plugin: task
    task: 'bootstrap'
    parameters:
      master: 'puppet.example.com'
      cacert_content: <cert>
``` 

### Expose existing behavior as a plugin

The existing behavior should be exposed as the `install_agent` plugin written in ruby. It should take no configuration for now.

## Questions
- Should bolt always use the `puppet_agent::version` task before running the `puppet_libraries` hook? Otherwise all tasks that would be used would need to optionally check for an agent which the examples don't do currently. Should we expose a second hook?
- Once one library hook is successful should we call the hook again for that target?

**Comment by lucywyman** [comment]
It should do the version check and install only if the puppet_agent feature is not present. Otherwise check the version, run the plugin if not already installed, and set the puppet_agent feature on the target.

**Comment by nmaludy** [comment]
Would be nice to support those of us who don't install the public Puppet repos. We run Red Hat Satellite and mirror the Puppet YUM repo interally. When a new host gets provisioned, it is registered with Satellite and the internal Puppet repo is automatically enabled. The current `apply_prep()` and `puppet_agent::install` tasks cause an issue because they want to manage/setup the public Puppet repo.

To work around this, we do
```puppet
run_task('package::linux', $nodes,
                name   => 'puppet-agent',
                action => 'install')
```

It would be great to have an option/configuration so that the public repo setup can be skipped.
