### ISSUE TITLE
Remove deprecations for Bolt 2.0

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1567]
## TODO
- [x] Create a 2.0 branch
- [x] Remove inventory v1 and target v1 objects. This includes updating spec tests and removing documentation. The `Bolt::Inventory` class should remain as an inventory factory. #1580 
- [x] Remove `future` logic. Update spec tests, and ensure documentation is correct with new behavior. Bolt should warn if the future config is set, and do nothing. #1590 
- [x] Remove deprecated features (anything that currently has a deprecation warning). #1590 
- [x] Update acceptance tests to pass with new Bolt. This includes reviewing the acceptance tests to determine what we need to keep. Anything that isn't platform or packaging dependent should be tested at the integration level. #1595 
- [x] Bump minimum ruby version to 2.5 #1546
- [x] Add warning message that v1 inventory file needs to be upgraded to v2
- [x] Remove plugin config (bolt_plugin.json) #1598
