### ISSUE TITLE
Package Bolt for Ubuntu 20.04

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1782]
## Use Case
With the release of Puppet 6.15, there is now puppet-agent support for Ubuntu 20.04. Bolt should release packages for Ubuntu 20.04.

### TODO

- [ ] Review and merge puppetlabs/puppet-runtime#335
       Builds bolt-runtime without pl-build-tools
- [ ] Review and merge puppetlabs/bolt-vanagon#135
       Adds ubuntu-20.04-amd64 platform
- [ ] Add ubuntu-20.04-amd64 to puppetlabs/ci-job-configs
- [ ] Package Bolt for Ubuntu 20.04
- [ ] Build and ship puppet-tools-release

**Comment by donoghuc** [comment]
Dont forget apply tests in acceptance will fail unless support is in puppet_agent module. I think you will need to update https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/tasks/install_shell.sh#L575
